version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dealstop
    ports:
    - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 20s
      retries: 10
    networks:
      - dealstop-network
  domain-transaction-server:
    container_name: dealstop-server
    build:
      context: .
      dockerfile: Dockerfile
    image: dealstop/ecomm
    ports:
    - '8080:8080'
    environment:
      MYSQL_HOST: mysql-local
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dealstop-network

networks:
  dealstop-network:
    driver: bridge