# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time

name: Push to docker hub

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - run: sudo service mysql start
      - run: mysql -uroot -proot -e 'create database dealstop'
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: mvn build
        run: mvn clean install
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: smudgal/pay-with-a-deal:0.0.1
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
